use super::combine_classes;
use std::collections::HashMap;

pub mod accessibility;
pub mod backgrounds;
pub mod borders;
pub mod effects;
pub mod filters;
pub mod flexbox_and_grid;
pub mod interactivity;
pub mod layout;
pub mod sizing;
pub mod spacing;
pub mod svg;
pub mod tables;
pub mod transforms;
pub mod transition_and_animation;
pub mod typography;

pub fn classes() -> HashMap<&'static str, &'static str> {
    combine_classes!(
        accessibility::forced_color_adjust::CLASSES,
        accessibility::screen_readers::CLASSES,
        backgrounds::background_attachment::CLASSES,
        backgrounds::background_clip::CLASSES,
        backgrounds::background_color::CLASSES,
        backgrounds::background_image::CLASSES,
        backgrounds::background_origin::CLASSES,
        backgrounds::background_position::CLASSES,
        backgrounds::background_repeat::CLASSES,
        backgrounds::background_size::CLASSES,
        backgrounds::gradient_color_stops::CLASSES,
        borders::border_color::CLASSES,
        borders::border_radius::CLASSES,
        borders::border_style::CLASSES,
        borders::border_width::CLASSES,
        borders::divide_color::CLASSES,
        borders::divide_style::CLASSES,
        borders::divide_width::CLASSES,
        borders::outline_color::CLASSES,
        borders::outline_offset::CLASSES,
        borders::outline_style::CLASSES,
        borders::outline_width::CLASSES,
        borders::ring_color::CLASSES,
        borders::ring_offset_color::CLASSES,
        borders::ring_offset_width::CLASSES,
        borders::ring_width::CLASSES,
        effects::background_blend_mode::CLASSES,
        effects::box_shadow::CLASSES,
        effects::box_shadow_color::CLASSES,
        effects::mix_blend_mode::CLASSES,
        effects::opacity::CLASSES,
        filters::backdrop_blur::CLASSES,
        filters::backdrop_brightness::CLASSES,
        filters::backdrop_contrast::CLASSES,
        filters::backdrop_grayscale::CLASSES,
        filters::backdrop_hue_rotate::CLASSES,
        filters::backdrop_invert::CLASSES,
        filters::backdrop_opacity::CLASSES,
        filters::backdrop_saturate::CLASSES,
        filters::backdrop_sepia::CLASSES,
        filters::blur::CLASSES,
        filters::brightness::CLASSES,
        filters::contrast::CLASSES,
        filters::drop_shadow::CLASSES,
        filters::grayscale::CLASSES,
        filters::hue_rotate::CLASSES,
        filters::invert::CLASSES,
        filters::saturate::CLASSES,
        filters::sepia::CLASSES,
        flexbox_and_grid::align_content::CLASSES,
        flexbox_and_grid::align_items::CLASSES,
        flexbox_and_grid::align_self::CLASSES,
        flexbox_and_grid::flex::CLASSES,
        flexbox_and_grid::flex_basis::CLASSES,
        flexbox_and_grid::flex_direction::CLASSES,
        flexbox_and_grid::flex_grow::CLASSES,
        flexbox_and_grid::flex_shrink::CLASSES,
        flexbox_and_grid::flex_wrap::CLASSES,
        flexbox_and_grid::gap::CLASSES,
        flexbox_and_grid::grid_auto_columns::CLASSES,
        flexbox_and_grid::grid_auto_flow::CLASSES,
        flexbox_and_grid::grid_auto_rows::CLASSES,
        flexbox_and_grid::grid_column::CLASSES,
        flexbox_and_grid::grid_row::CLASSES,
        flexbox_and_grid::grid_template_columns::CLASSES,
        flexbox_and_grid::grid_template_rows::CLASSES,
        flexbox_and_grid::justify_content::CLASSES,
        flexbox_and_grid::justify_items::CLASSES,
        flexbox_and_grid::justify_self::CLASSES,
        flexbox_and_grid::order::CLASSES,
        flexbox_and_grid::place_content::CLASSES,
        flexbox_and_grid::place_items::CLASSES,
        flexbox_and_grid::place_self::CLASSES,
        interactivity::accent_color::CLASSES,
        interactivity::appearance::CLASSES,
        interactivity::caret_color::CLASSES,
        interactivity::cursor::CLASSES,
        interactivity::pointer_events::CLASSES,
        interactivity::resize::CLASSES,
        interactivity::scroll_behavior::CLASSES,
        interactivity::scroll_margin::CLASSES,
        interactivity::scroll_padding::CLASSES,
        interactivity::scroll_snap_align::CLASSES,
        interactivity::scroll_snap_stop::CLASSES,
        interactivity::scroll_snap_type::CLASSES,
        interactivity::touch_action::CLASSES,
        interactivity::user_select::CLASSES,
        interactivity::will_change::CLASSES,
        layout::aspect_ratio::CLASSES,
        layout::box_decoration_break::CLASSES,
        layout::box_decoration_sizing::CLASSES,
        layout::box_display::CLASSES,
        layout::break_after::CLASSES,
        layout::break_before::CLASSES,
        layout::break_inside::CLASSES,
        layout::clear::CLASSES,
        layout::columns::CLASSES,
        layout::float::CLASSES,
        layout::isolation::CLASSES,
        layout::object_fit::CLASSES,
        layout::object_position::CLASSES,
        layout::overflow::CLASSES,
        layout::overflowscroll::CLASSES,
        layout::position::CLASSES,
        layout::top_right_bottom_left::CLASSES,
        layout::visibility::CLASSES,
        layout::z_index::CLASSES,
        sizing::height::CLASSES,
        sizing::max_height::CLASSES,
        sizing::max_width::CLASSES,
        sizing::min_height::CLASSES,
        sizing::min_width::CLASSES,
        sizing::size::CLASSES,
        sizing::width::CLASSES,
        spacing::margin::CLASSES,
        spacing::padding::CLASSES,
        spacing::space_between::CLASSES,
        svg::fill::CLASSES,
        svg::stroke::CLASSES,
        svg::stroke_width::CLASSES,
        tables::border_collapse::CLASSES,
        tables::border_spacing::CLASSES,
        tables::caption_side::CLASSES,
        tables::table_layout::CLASSES,
        transforms::rotate::CLASSES,
        transforms::scale::CLASSES,
        transforms::skew::CLASSES,
        transforms::transform_origin::CLASSES,
        transforms::translate::CLASSES,
        transition_and_animation::animation::CLASSES,
        transition_and_animation::transition_delay::CLASSES,
        transition_and_animation::transition_duration::CLASSES,
        transition_and_animation::transition_property::CLASSES,
        transition_and_animation::transition_timing_function::CLASSES,
        typography::content::CLASSES,
        typography::font_family::CLASSES,
        typography::font_size::CLASSES,
        typography::font_smoothing::CLASSES,
        typography::font_style::CLASSES,
        typography::font_variant_numeric::CLASSES,
        typography::font_weight::CLASSES,
        typography::hyphens::CLASSES,
        typography::letter_spacing::CLASSES,
        typography::line_clamp::CLASSES,
        typography::line_height::CLASSES,
        typography::line_style_image::CLASSES,
        typography::line_style_position::CLASSES,
        typography::line_style_type::CLASSES,
        typography::text_align::CLASSES,
        typography::text_color::CLASSES,
        typography::text_decoration::CLASSES,
        typography::text_decoration_color::CLASSES,
        typography::text_decoration_style::CLASSES,
        typography::text_decoration_thickness::CLASSES,
        typography::text_indent::CLASSES,
        typography::text_overflow::CLASSES,
        typography::text_transform::CLASSES,
        typography::text_underline_offset::CLASSES,
        typography::text_wrap::CLASSES,
        typography::vertical_align::CLASSES,
        typography::whitespace::CLASSES,
        typography::word_break::CLASSES
)}