use phf::phf_map;

pub static CLASSES: phf::Map<&'static str, &'static str> = phf_map! {
    "backdrop-opacity-0" => "backdrop-filter: opacity(0);",
    "backdrop-opacity-5" => "backdrop-filter: opacity(0.05);",
    "backdrop-opacity-10" => "backdrop-filter: opacity(0.1);",
    "backdrop-opacity-15" => "backdrop-filter: opacity(0.15);",
    "backdrop-opacity-20" => "backdrop-filter: opacity(0.2);",
    "backdrop-opacity-25" => "backdrop-filter: opacity(0.25);",
    "backdrop-opacity-30" => "backdrop-filter: opacity(0.3);",
    "backdrop-opacity-35" => "backdrop-filter: opacity(0.35);",
    "backdrop-opacity-40" => "backdrop-filter: opacity(0.4);",
    "backdrop-opacity-45" => "backdrop-filter: opacity(0.45);",
    "backdrop-opacity-50" => "backdrop-filter: opacity(0.5);",
    "backdrop-opacity-55" => "backdrop-filter: opacity(0.55);",
    "backdrop-opacity-60" => "backdrop-filter: opacity(0.6);",
    "backdrop-opacity-65" => "backdrop-filter: opacity(0.65);",
    "backdrop-opacity-70" => "backdrop-filter: opacity(0.7);",
    "backdrop-opacity-75" => "backdrop-filter: opacity(0.75);",
    "backdrop-opacity-80" => "backdrop-filter: opacity(0.8);",
    "backdrop-opacity-85" => "backdrop-filter: opacity(0.85);",
    "backdrop-opacity-90" => "backdrop-filter: opacity(0.9);",
    "backdrop-opacity-95" => "backdrop-filter: opacity(0.95);",
    "backdrop-opacity-100" => "backdrop-filter: opacity(1);",
};