[components]
  [components.backgrounds]
    [components.backgrounds.background_attachment]
    url = "https://tailwindcss.com/docs/background-attachment"
    [components.backgrounds.background_clip]
    url = "https://tailwindcss.com/docs/background-clip"
    [components.backgrounds.background_color]
    url = "https://tailwindcss.com/docs/background-color"
    [components.backgrounds.background_origin]
    url = "https://tailwindcss.com/docs/background-origin"
    [components.backgrounds.background_position]
    url = "https://tailwindcss.com/docs/background-position"
    [components.backgrounds.background_repeat]
    url = "https://tailwindcss.com/docs/background-repeat"
    [components.backgrounds.background_size]
    url = "https://tailwindcss.com/docs/background-size"
    [components.backgrounds.background_image]
    url = "https://tailwindcss.com/docs/background-image"
    [components.backgrounds.background_color_stops]
    url = "https://tailwindcss.com/docs/gradient-color-stops"
